# Generated by Django 5.0.14 on 2025-09-09 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriber_id', models.AutoField(db_column='SubscriberID', primary_key=True, serialize=False)),
                ('subscriber_name', models.CharField(db_column='SubscriberName', max_length=255)),
            ],
            options={
                'db_table': 'Sheet1$',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriberToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField(db_index=True, help_text='Reference to subscriber ID from external table')),
                ('token', models.CharField(help_text='URL-safe random string', max_length=32, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscriber Token',
                'verbose_name_plural': 'Subscriber Tokens',
                'db_table': 'subscriber_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscriber_id', 'is_active'], name='subscriber__subscri_c86767_idx'), models.Index(fields=['token', 'is_active'], name='subscriber__token_01d397_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscriberPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField(db_index=True, help_text='Reference to subscriber ID from external table')),
                ('permission_level', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read/Write'), ('admin', 'Administrator')], default='read', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscriber Permission',
                'verbose_name_plural': 'User Subscriber Permissions',
                'db_table': 'user_subscriber_permissions',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user', 'subscriber_id', 'is_active'], name='user_subscr_user_id_68c5d8_idx'), models.Index(fields=['subscriber_id', 'is_active'], name='user_subscr_subscri_412b11_idx')],
                'unique_together': {('user', 'subscriber_id')},
            },
        ),
    ]
