# Generated by Django 5.0.14 on 2025-09-10 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribertoken',
            name='binding_date',
            field=models.DateTimeField(blank=True, help_text='When this token was used for binding', null=True),
        ),
        migrations.AddField(
            model_name='subscribertoken',
            name='binding_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which binding was performed', null=True),
        ),
        migrations.AddField(
            model_name='subscribertoken',
            name='bound_user',
            field=models.ForeignKey(blank=True, help_text='User who used this token for permanent binding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binding_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscribertoken',
            name='is_used_for_binding',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this token has been used for permanent user-subscriber binding'),
        ),
    ]
