# Generated by Django 5.0.14 on 2025-09-10 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_subscribertoken_binding_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField(db_index=True, help_text='Reference to subscriber ID from external table')),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('individual_records', models.PositiveIntegerField(default=0)),
                ('corporate_records', models.PositiveIntegerField(default=0)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('individual_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('corporate_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('individual_txt_path', models.CharField(blank=True, max_length=500, null=True)),
                ('corporate_txt_path', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Session',
                'verbose_name_plural': 'Upload Sessions',
                'db_table': 'upload_sessions',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'uploaded_at'], name='upload_sess_user_id_92d5e7_idx'), models.Index(fields=['subscriber_id', 'uploaded_at'], name='upload_sess_subscri_b0439b_idx'), models.Index(fields=['status', 'uploaded_at'], name='upload_sess_status_d1e11a_idx')],
            },
        ),
    ]
