# Generated by Django 5.0.14 on 2025-09-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_uploadsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='corporate_credit_matched',
            field=models.PositiveIntegerField(default=0, help_text='Corporate credit records successfully matched'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='corporate_credit_total',
            field=models.PositiveIntegerField(default=0, help_text='Total valid corporate credit records'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='corporate_credit_unmerged',
            field=models.PositiveIntegerField(default=0, help_text='Corporate credit records that could not be merged'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='individual_credit_matched',
            field=models.PositiveIntegerField(default=0, help_text='Individual credit records successfully matched'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='individual_credit_total',
            field=models.PositiveIntegerField(default=0, help_text='Total valid individual credit records'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='individual_credit_unmerged',
            field=models.PositiveIntegerField(default=0, help_text='Individual credit records that could not be merged'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='total_credit_unmerged',
            field=models.PositiveIntegerField(default=0, help_text='Total credit records that could not match to any borrower type'),
        ),
    ]
