# Generated by Django 5.0.14 on 2025-09-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_uploadsession_corporate_credit_matched_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsession',
            name='corporate_credit_total',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='corporate_credit_unmerged',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='individual_credit_total',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='individual_credit_unmerged',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='total_credit_unmerged',
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='total_credit_records',
            field=models.PositiveIntegerField(default=0, help_text='Total valid credit records in the credit file'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='total_credit_unmatched',
            field=models.PositiveIntegerField(default=0, help_text='Credit records that could not match to any borrower type'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='corporate_credit_matched',
            field=models.PositiveIntegerField(default=0, help_text='Credit records successfully matched to corporate borrowers'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='individual_credit_matched',
            field=models.PositiveIntegerField(default=0, help_text='Credit records successfully matched to individual borrowers'),
        ),
    ]
