# Generated by Django 5.0.14 on 2025-09-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_uploadsession_corporate_credit_matched_and_more'),
        ('auto', '0005_remove_uploadsession_corporate_credit_total_and_more'),
    ]

    operations = [
    ]
