# Generated by Django 5.0.14 on 2025-09-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_merge_20250923_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsession',
            name='total_credit_records',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='total_credit_unmatched',
        ),
    ]
