# Generated by Django 5.0.14 on 2025-09-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_remove_uploadsession_total_credit_records_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsession',
            name='corporate_credit_matched',
            field=models.PositiveIntegerField(default=0, help_text='Number of corporate records with credit matches'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='individual_credit_matched',
            field=models.PositiveIntegerField(default=0, help_text='Number of individual records with credit matches'),
        ),
    ]
