# Generated by Django 5.0.14 on 2025-10-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_alter_uploadsession_corporate_credit_matched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='corporate_unmatched',
            field=models.PositiveIntegerField(default=0, help_text='Number of corporate records that could not be matched'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='individual_unmatched',
            field=models.PositiveIntegerField(default=0, help_text='Number of individual records that could not be matched'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='total_unmatched',
            field=models.PositiveIntegerField(default=0, help_text='Total number of unmatched records'),
        ),
    ]
