# Generated by Django 5.0.14 on 2025-10-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_add_unmatched_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsession',
            name='corporate_unmatched',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='individual_unmatched',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='total_unmatched',
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='unmatched_credit_records',
            field=models.PositiveIntegerField(default=0, help_text='Number of credit records that could not be matched to any borrower'),
        ),
    ]
