# Generated by Django 5.2.5 on 2025-10-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0010_remove_uploadsession_corporate_unmatched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='original_file_path',
            field=models.CharField(blank=True, help_text='Path to the original unmodified uploaded file for dispute resolution and audit purposes', max_length=500, null=True),
        ),
    ]
