# Generated by Django 5.1.3 on 2025-10-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0011_add_original_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='activity_log',
            field=models.JSONField(blank=True, default=list, help_text='Timestamped log of processing activities for audit trail'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='commercial_candidates_count',
            field=models.IntegerField(default=0, help_text='Number of potential commercial entities found in consumer records'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='consumer_candidates_count',
            field=models.IntegerField(default=0, help_text='Number of potential consumer entities found in commercial records'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='current_message',
            field=models.TextField(blank=True, help_text='Current processing message for real-time updates'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='has_verification_candidates',
            field=models.BooleanField(default=False, help_text='Whether this upload has records requiring human verification'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='processing_stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('upload_validation', 'File Upload & Validation'), ('data_mapping', 'Data Mapping & Preparation'), ('data_cleaning', 'Data Cleaning & Transformation'), ('credit_matching', 'Credit Matching & Classification'), ('awaiting_verification', 'Awaiting Human Verification'), ('post_verification', 'Finalization After Verification'), ('output_generation', 'Output Generation'), ('completed', 'Completed')], default='pending', help_text='Current processing stage for detailed progress tracking', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Overall progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='verification_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when human verification was completed', null=True),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('awaiting_verification', 'Awaiting Verification'), ('finalizing', 'Finalizing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
