# Generated by Django 5.1.3 on 2025-10-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0012_uploadsession_activity_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='processing_data',
            field=models.TextField(blank=True, help_text='JSON storage for processing data when using async workflow', null=True),
        ),
        migrations.AlterModelTable(
            name='subscriber',
            table='Sheet1',
        ),
    ]
