# Generated by Django 5.1.3 on 2025-11-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0013_uploadsession_processing_data_alter_subscriber_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='corporate_output_format',
            field=models.CharField(blank=True, help_text="Output format for corporate sheet: 'xlsx' or 'txt'", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='individual_output_format',
            field=models.CharField(blank=True, help_text="Output format for individual sheet: 'xlsx' or 'txt'", max_length=10, null=True),
        ),
    ]
