# Generated by Django 5.1.3 on 2025-11-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0014_uploadsession_corporate_output_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='reporting_month',
            field=models.IntegerField(blank=True, help_text='User-selected reporting month (1-12) for output filename generation', null=True),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='reporting_year',
            field=models.IntegerField(blank=True, help_text='User-selected reporting year for output filename generation', null=True),
        ),
    ]
