# Generated by Django 5.1.3 on 2025-12-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0015_uploadsession_reporting_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribertoken',
            name='created_by',
            field=models.CharField(blank=True, help_text='Username of the creator (stored as text to allow cross-DB compatibility)', max_length=150, null=True),
        ),
        migrations.AlterModelTable(
            name='subscriber',
            table='Sheet1$',
        ),
    ]
