# Generated by Django 5.1.3 on 2025-12-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0016_alter_subscribertoken_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriberpermission',
            name='granted_by',
            field=models.CharField(blank=True, help_text='Username of the granter (stored as text)', max_length=150, null=True),
        ),
    ]
