"""
Django settings for fcbauto project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_q',
    'auto',
    'acctmgt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'acctmgt.middleware.SubscriberSessionMiddleware',  # Custom subscriber validation middleware
    #'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'fcbauto.urls'

INTERNAL_IPS = [
    '127.0.0.1',  # Localhost
    # You can add other IPs if needed, for example, if you're using Docker or a VM
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'acctmgt.context_processors.subscriber_context',  # Custom context processor for subscriber binding
            ],
        },
    },
]

WSGI_APPLICATION = 'fcbauto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Multiple database configuration
DATABASES = {
    # SQLite for Django internal operations (users, sessions, upload tracking, Q tasks)
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    # MSSQL for external Subscribers lookup (read-only)
    'subscribers_db': {
        'ENGINE': 'mssql',
        'NAME': config('DB_SUBSCRIBERS_NAME', default='Subscribers'),
        'HOST': config('DB_SUBSCRIBERS_HOST', default='IT-FAITHO\\SQLEXPRESS'),
        'USER': config('DB_SUBSCRIBERS_USER', default='r'),
        'PASSWORD': config('DB_SUBSCRIBERS_PASSWORD', default='1'),
        'PORT': config('DB_SUBSCRIBERS_PORT', default=''),
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'Trusted_connection': 'yes',
            'TrustServerCertificate': 'yes',
            'Encrypt': 'no',
        },
    }
}

# Database router to direct Subscriber model queries to MSSQL
DATABASE_ROUTERS = ['fcbauto.database_router.SubscriberDatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'auto/static'),
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication settings
LOGIN_URL = 'acctmgt:login'  # Using the namespaced URL
LOGIN_REDIRECT_URL = 'auto:dashboard'  # Using the namespaced URL for dashboard
LOGOUT_REDIRECT_URL = 'acctmgt:login'  # Using the namespaced URL


# Django Q Cluster Configuration
Q_CLUSTER = {
    'name': 'credit_bureau_processing',
    'workers': 4,
    'recycle': 500,
    'timeout': 36000,  # 10 hours timeout for large file processing with chunking
    'retry': 37000,  # Retry window - must be larger than timeout (10 hours)
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',  # Use Django ORM as broker (SQLite)
    'catch_up': False,
    'save_limit': 250,
    'ack_failures': True,
    'max_attempts': 1,
    'attempt_count': 1,
}


